version: "3"

services:
  nginx:
    container_name: nginx
    build: ./services/nginx
    ports:
      - $NGINX_HTTP_HOST_PORT:80
      - $NGINX_HTTPS_HOST_PORT:443
    volumes:
      - $CODE_DIR:/data/www
      - $NGINX_CONFIG_DIR:/etc/nginx/conf.d
      - $NGINX_CONFIG_FILE:/etc/nginx/nginx/conf
      - $NGINX_CONFIG_FASTCGI_PARMS:/etc/nginx/fastcgi_params
      - $NGINX_CONFIG_FASTCGI_PHP:/etc/nginx/fastcgi-php.conf
      - $NGINX_CONFIG_SSL_DIR:/etc/nginx/ssl
      - $NGINX_LOG_DIR:/var/log/nginx/
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    build: ./services/php/$PHP_VERSION/fpm
    volumes:
      - $CODE_DIR:/data/www
      - ./services/php/$PHP_VERSION/conf/php.ini:/usr/local/etc/php/php.ini
      - $PHP_CACERT_FILE:/usr/local/etc/php/cacert.pem
      - ./services/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./services/supervisor/conf.d/:/etc/supervisor/conf.d/
    ports:
      - $PHP_SWOOLE_PORT:8181
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    build: ./services/mysql/$MYSQL_VERSION
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_HOST_PORT:3306
    volumes:
      - $MYSQL_DATA_DIR:/var/lib/mysql
      - ./services/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  redis:
    container_name: redis
    build: ./services/redis
    volumes:
      - $REDIS_DATA_DIR:/data/:rw
      - $REDIS_CONF_FILE:/usr/local/etc/redis/redis.conf
    ports:
      - $REDIS_HOST_PORT:6379
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - $MONGO_DATA_DIR:/data/:rw
      - $MONGO_ENTRYPOINT_DIR:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - $MONGO_HOST_PORT:27017
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.2.1
    environment:
      - node.name=docker-lndx
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=docker-lndx
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - $ES_DATA_DIR:/usr/share/elasticsearch/data
      - $ES_LOGS_DIR:/usr/share/elasticsearch/logs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - $ES_HOST_PORT:9200


